### ISSUE TITLE
El servicio Crashea cuando busca subtitulos.

### ISSUE THREAD

**Issue by ghost** [josecurioso/service.subtitles.tusubtitulo#3]
Hola.
Estoy utilizando el servicio con kodi 17.3 con Emby Server pero marca error al momento de buscar cualquier subtitulo, he revisado con otros servicios de subtitulos y funcionan correctamente. ya trate de borrar todo y volver a instalar y el error persiste. aqui te paso mi log ojala sea de ayuda.
Saludos!.

20:02:19.468 T:6768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('items',)
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\service.subtitles.tusubtitulo\service.py", line 182, in <module>
                                                Search(item)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\service.subtitles.tusubtitulo\service.py", line 44, in Search
                                                subs = search_tvshow(item['tvshow'], item['season'], item['episode'], item['2let_language'], item['file_original_path'])
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\service.subtitles.tusubtitulo\resources\lib\SubEsUtilities.py", line 24, in search_tvshow
                                                subs.extend(getAllSubInfo(buildURL(tvshow, season, episode), tvshow, season, episode))
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\service.subtitles.tusubtitulo\resources\lib\SubEsUtilities.py", line 43, in buildURL
                                                showIdWord = data["items"][0]["title"].strip().strip("TuSubtitulo").strip().strip("-").strip().replace(" ", "-")
                                            KeyError: ('items',)
                                            -->End of Python script error report<--

**Comment by josecurioso** [comment]
Buenas, estoy en ello. ¿Hay alguna serie en concreto que te haya fallado? Creo que ya he encontrado donde puede estar el error pero igualmente intenta instalando la última versión porque a mi me está funcionando.

**Comment by josecurioso** [comment]
No soy capaz de replicar el error, de todas formas en un rato habrá una nueva release con algunas mejoras para evitarlo.

**Comment by ghost** [comment]
Hola.
Estube probando la nueva version con varias instalaciones que tengo y esta funcionando perfectamente y sin ningun tipo de error.
Muchas gracias por tu ayuda y por el tiempo que le dedicas a este servicio..
Saludos!
